pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main',
    credentialsId: 'github-token',  // This is the ID from Jenkins credentials
    url: 'https://github.com/ThePoojaDas/ci-cd-webapp.git'

            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t your-dockerhub-username/my-webapp:latest .'
            }
        }
        stage('Push to Docker Hub') {
            steps {
                sh 'docker push your-dockerhub-username/my-webapp:latest'
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f deployment.yaml'
            }
        }
    }
}
