name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t your-dockerhub-username/ci-cd-webapp:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "your-dockerhub-username" --password-stdin
          docker push your-dockerhub-username/ci-cd-webapp:latest

      - name: Deploy to Kubernetes
        run: kubectl apply -f kubernetes-deployment.yaml
