name: CI Pipeline  # Name of the workflow

on:
  push:
    branches:
      - main  # Runs this workflow when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on a Linux machine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Gets your code from GitHub

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Installs Python 3.9

      - name: Install Dependencies
        run: |
          pip install -r app/requirements.txt  # Installs required dependencies

      - name: Run Tests
        run: |
          pytest app/tests/  # Runs automated tests

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-app:latest
